-- Host skeleton generation/reset support.
-- Skeleton values themselves are generated by the Go world engine from the
-- world's canonical seed; this migration only adds persisted reset generation.
ALTER TABLE hosts
    ADD COLUMN IF NOT EXISTS generation integer NOT NULL DEFAULT 0;
